name: anota_cep
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  dartz:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  asyncstate: ^2.0.0
  flutter_getit: ^2.0.0-dev.12
  dio: ^5.7.0
  path: ^1.9.0
  sqflite: ^2.4.1
  lottie: ^3.1.3
  loading_animation_widget: ^1.3.0
  google_maps_flutter: ^2.10.0
  brasil_fields: ^1.15.0
  flutter_launcher_icons: ^0.14.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
